### ISSUE TITLE
Deployment Conflicts

### ISSUE THREAD

**Issue by geeky01adarsh** [aaveggupta/DSA-Marathon#12]
On heading towards deployment there are many deployments and may create some kind of confusion. Can you please resolve that?

**Comment by aaveggupta** [comment]
Yes, absolutely! Could you please elaborate on this issue a little bit more, or if you have any screenshots relating to this issue, please submit them here and I'll take a look at it!!

**Comment by geeky01adarsh** [comment]
![Screenshot (394)_LI](https://user-images.githubusercontent.com/74068552/132268591-0d5ac059-44f4-4f18-b646-8af2017112e5.jpg)
![Screenshot (395)](https://user-images.githubusercontent.com/74068552/132268592-1e82ff4a-e209-4aed-906e-39e1e8775e2d.png)
Please have a look. My issue is that currently there is more than one gh-page active and every page has different data. That is visible in the gh-pages pages and already we have 6-7 deployments before the activity log starts. 
Hope you understood what I wanted to convey!

**Comment by aaveggupta** [comment]
Actually, I have deployed a bot on this repo whose task is to generate web-page whenever someone makes a PR. With this, I don't have to go through the code I can check on the go what changes they are trying to make!
The final web deployment can be seen on GitHub Pages section in environments, and the pages which are in production are just a preview of PR that someone has made!

**Comment by geeky01adarsh** [comment]
> Actually, I have deployed a bot on this repo whose task is to generate web-page whenever someone makes a PR. With this, I don't have to go through the code I can check on the go what changes they are trying to make!
> The final web deployment can be seen on GitHub Pages section in environments, and the pages which are in production are just a preview of PR that someone has made!

Ok thanks 😃
